# Environnment variables are loaded from ./.env
# If you do not have a .env copy and rename the .env.sample which contains a correct default configuration.
version: "3"
services:
  adminer:
    image: adminer
    env_file:
      - .env
    ports:
      - "${ADMINER_EXPOSED_PORT}:8080"
