# This is a Work In Progress
name: zReusable Scalingo execute an application task in a one-off container

on:
  workflow_call:
    inputs:
      application-reference-name:
        required: true
        type: string

      task:
        required: true
        type: string

    outputs:
      task-output:
        description: "The task stdout output"
        value: ${{ jobs.execute-application-task.outputs.task-output }}

    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  execute-application-task:
    name: Execute an application task in one-off container
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli
    outputs:
      task-output: ${{ steps.execute-task.outputs.task-output }}
    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: Execute the task on an application clone
        id: execute-task
        run: |
          set +e
          scalingo --app ${{ inputs.application-reference-name }} run bash -c "ls && ${{ inputs.task }}"
          set -e
          echo "::set-output name=task-output::$?"
