name: zReusable Discord Deployment Notify Workflow
# Post a notification that a deployment has been completed on the linked discord channel

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      deployed-domain:
        required: true
        type: string
      deployer-name:
        required: true
        type: string

    secrets:
      DISCORD_NOTIFY_HOOK_URL:
        required: true

jobs:
  discord-notify-instance-url:
    runs-on: ubuntu-latest
    steps:
      - name: Notify discord hooked canal
        run: |
          curl --header "Content-Type:application/json" -d "{\"username\":\"${{ inputs.deployer-name }}\", \"content\":\"Une nouvelle version pour ${{ inputs.application-name }} est disponible.\n [Tester la démo](https://${{ inputs.deployed-domain }})  \"}" ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}
