name: Reusable Discord Deployment Notify Workflow

on:
  workflow_call:
    inputs:
      notifier-display-name:
        required: true
        type: string
      task-result:
        required: true
        type: string

    secrets:
      DISCORD_NOTIFY_HOOK_URL:
        required: true

jobs:
  discord-notify-instance-url:
    runs-on: ubuntu-latest
    steps:
      - name: Notify discord hooked canal
        run: |
          curl --header "Content-Type:application/json" -d "{\"username\":\"${{ inputs.notifier-display-name }}\", \"content\":\"Résutat de l'execution' ${{ inputs.task-result }} \"}" ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}
